# WebRTC ICE服务器配置
stun_servers:
  - url: "stun:stun.l.google.com:19302"
  - url: "stun:stun.cloudflare.com:3478"

turn_servers:
  # 我们自己的TURN服务器
  - url: "turn:115.159.125.146:3478"
  # - url: "turn:127.0.0.1:3478"
    username: "maya"
    credential: "sorrow2713"

# WebRTC连接配置
rtc_config:
  ice_candidate_pool_size: 10
  bundle_policy: "max-bundle"
  rtcp_mux_policy: "require"

# 服务器连接配置
server_config:
  server_url: "ws://115.159.125.146:3000/ws"
  # server_url: "ws://127.0.0.1:3000/ws"
  client_id: "890e78618669b636"
  auth_code: "11111" 