[package]
name = "remote-control-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
mac_address = { workspace = true }
warp = { workspace = true }
tokio-stream = "0.1"
dashmap = "5.5"
serde_yaml = "0.9" 
tokio-rustls = "0.24"
rustls-pemfile = "1.0"
rcgen = "0.11"
hyper = "0.14"
log = { workspace = true }
env_logger = { workspace = true } 