[package]
name = "signals-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true }
anyhow = { workspace = true }
dashmap = "6.1"
log = { workspace = true }
env_logger = { workspace = true }
clap = { version = "4.5", features = ["derive"] } 